### ISSUE TITLE
Virtual Reality Refactoring

### ISSUE THREAD

**Issue by SwedishSock** [Chainsawkitten/LargeGameProjectEngine#588] opened 2017-10-16 11:32 UTC
As a software architect I would find value in having a component that represents a VR device (HMD or controller) whose responsibility is to simply collect sensor data to update its entity accordingly.

**Comment by Chainsawkitten** [comment] 2017-10-16 11:40
Duplicate of #499

**Closed** 2017-10-25 12:05 UTC
Labels: Engine, Game, Refactor, Video
