### ISSUE TITLE
Deleting light sources does not change the current light calculations.

### ISSUE THREAD

**Issue by abdominator** [Chainsawkitten/LargeGameProjectEngine#428] opened 2017-10-06 11:39 UTC
Light on current mesh still looks the same even after deleting the light source.

**Comment by Chainsawkitten** [comment] 2017-10-19 10:57
Can't reproduce. Fixed?

**Comment by LarsIngo** [comment] 2017-10-26 08:03
Should be fixed when light struct was padded. Can't reproduce.

**Closed** 2017-10-26 08:02 UTC
Labels: Bug - Not severe
