### ISSUE TITLE
Mouse picking is active while mouse button is pressed.

### ISSUE THREAD

**Issue by abdominator** [Chainsawkitten/LargeGameProjectEngine#430] opened 2017-10-06 12:23 UTC
Mouse Picking is triggered while left mouse button is down and intersecting another Entity. Causing problems when translating mesh using the gizmo tool.

**Comment by Chainsawkitten** [comment] 2017-10-06 12:43
Duplicate of #411

**Closed** 2017-10-06 12:43 UTC
Labels: Bug - Not severe
