### ISSUE TITLE
Memory leaks from 

### ISSUE THREAD

**Issue by ludvigarlebrink** [Chainsawkitten/LargeGameProjectEngine#169] opened 2017-09-15 09:20 UTC
Recreate:
Open / Create a hymn
Press f5 multiple times (around 100).
The memory usage has severely gone up and the application runs very slow.

**Comment by Chainsawkitten** [comment] 2017-09-15 09:39
Duplicate of #153

**Closed** 2017-09-15 09:39 UTC
Labels: Bug - Severe, Editor
