### ISSUE TITLE
Editor camera (far clipping plane)

### ISSUE THREAD

**Issue by LarsIngo** [Chainsawkitten/LargeGameProjectEngine#281] opened 2017-09-26 07:34 UTC
As a user I want the editor camera to have a greater distance to the far clipping plane.
Either by setting it by myself in the editor, or set a greater distance direct in the code.

**Comment by andens** [comment] 2017-10-16 07:04
Duplicate of #138

**Closed by andens** 2017-10-16 07:04 UTC
Labels: Duplicate, Editor
